### ISSUE TITLE
Modifier keys not working in the editor on macOS

### ISSUE THREAD

**Issue by bkirz** [ClubFantastic/stepmania#2]
## Summary
Modifier keys (at least ctrl/shift) don't seem to be working. I've only tested in the editor, since I don't know of other parts of SM that use modifiers, but it's possible that this is a global issue.

## Environment
- macOS Catalina 10.15.7 (19H524)
- MacBook Air (Retina, 13-inch, 2020)
- StepMania-5.1 built from ec8664a518
- Club Fantastic Theme, v4.9.1

## Steps to reproduce

To confirm ctrl doesn't work:
- Open a song in the editor.
- Press down to lower the receptors one quarter note.
- Hold ctrl, press up. Expected behavior is that the notefield zooms in/expands. Instead, the receptors move up a quarter note, ignoring held ctrl.

To confirm shift doesn't work:
- Open a song in the editor.
- Hold shift/fn and press F10.
- Save the file and open the .ssc in a text editor. Observe that a stop was added (normal F10 behavior) instead of a delay (normal shift+F10 behavior).

**Comment by bkirz** [comment]
As an extra data point, I've replicated this on a different machine running Big Sur.
Specs:
* MacBook (Retina, 12-inch, 2017)
* macOS Big Sur 11.2.2 (20D80)
* StepMania-5.1 built from ec8664a
* Default SM5 theme

**Comment by ghost** [comment]
This was actually fixed in commit c925ba7b5f028f12a1a502a21ada950c423cca3f—I built the wrong version for @bkirz for testing on Catalina/Big Sur. Recommend we just close this issue since the aforementioned commit was already merged into clubfantastic's branch of StepMania.
